name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-unix-makefiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print CMake Version
        run: cmake --version
      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles" -S ${{github.workspace}} -B ${{github.workspace}}/cmake-build
      - name: Build
        run: cmake --build ${{github.workspace}}/cmake-build

  build-visual-studio:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v3
      - name: Print CMake Version
        run: cmake --version
      - name: Configure CMake
        run: cmake -G "Visual Studio 17 2022" -A x64 -S ${{github.workspace}} -B ${{github.workspace}}\cmake-build
      - name: Build
        run: cmake --build ${{github.workspace}}\cmake-build --config Debug
