name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-unix-makefiles:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v3
      - name: Print CMake Version
        run: cmake --version
      - name: Configure CMake
        run: cmake -G "Unix Makefiles" -B cmake-build
      - name: Build
        run: cmake --build cmake-build
      - name: Test
        working-directory: ${{github.workspace}}/cmake-build
        run: ctest

  build-visual-studio:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
        working-directory: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v3
      - name: Print CMake Version
        run: cmake --version
      - name: Configure CMake
        run: cmake -G "Visual Studio 17 2022" -A x64 -B cmake-build
      - name: Build
        run: cmake --build cmake-build --config Debug
      - name: Test
        working-directory: ${{github.workspace}}\cmake-build
        run: ctest -C Debug
